version: "2"
services:
  web:
    image: yoshz/apache-php:7.0
    links:
      - db:database
    volumes:
     - ./docker/phpconf/apache2:/etc/php/7.0/apache2
     - ./docker/sites-avaliable/:/etc/apache2/sites-available/
     - ./www/:/var/www/
    ports:
      - "80:80"
  db:
    extends:
      file: docker-common-configs.yaml
      service: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: alfonso
      MYSQL_PASSWORD: alfonso
    ports:
      - "3307:3306"


